In [1]:
import cv2
import numpy as np
import pandas as pd
import numpy as np
import mediapipe as mp
import glob

# final code

In [2]:
#점수 구하는 공식
def euclid_distance(train, test):
    euclid_list = []

    if not np.isnan(train).any() and np.isnan(test).any():
        return 0

    for x, y in zip(train, test):
        cossim = np.dot(x, y) / (np.linalg.norm(x)*np.linalg.norm(y))
        euc_d = np.sqrt(2*(1-cossim))
        score = 100 - (100 * (euc_d)/2)
        euclid_list.append(score)

    return np.nanmean(euclid_list)

In [3]:
#전처리와 점수까지 한번에
def euclid_score(train, test):
    #test = origin_rate(test)
    #test = box_perspective(test)
    score_list=[]
    for idx in range(min(train.shape[0],test.shape[0])):
        train_v = train[idx]
        #test_joint = test.iloc[idx].values.reshape(33,2)
        #test_v = vector_transform(test_joint)
        test_v = test[idx]
        score = euclid_distance(train_v, test_v)
        score_list.append(score)
    return np.nanmean(score_list)

In [4]:
import warnings

warnings.filterwarnings(action='ignore') 

# 1. baby

In [5]:
names = ['baby']

train = np.load("./video/vector_npy/vector_baby.npy")

wrong_scores = []
for name in names:
    paths = glob.glob(f"./직촬편집/{name}/*.npy")
    for path in paths:
        test = np.load(path)
        score = str(round(euclid_score(train, test)))
        wrong_scores.append(score)

wrong_scores = np.array(wrong_scores, dtype=np.int64)
print(wrong_scores)
print(wrong_scores.mean())

[69 73 74 67 69]
70.4


# 2. bottom

In [6]:
names = ['bottom']

train = np.load("./video/vector_npy/vector_bottom.npy")

wrong_scores = []
for name in names:
    paths = glob.glob(f"./직촬편집/{name}/*.npy")
    for path in paths:
        test = np.load(path)
        score = str(round(euclid_score(train, test)))
        wrong_scores.append(score)

wrong_scores = np.array(wrong_scores, dtype=np.int64)
print(wrong_scores)
print(wrong_scores.mean())

[71 72 71 65 59]
67.6


# 3. goodmorning

In [7]:
names = ['goodmorning']

train = np.load("./video/vector_npy/vector_goodmorning.npy")

wrong_scores = []
for name in names:
    paths = glob.glob(f"./직촬편집/{name}/*.npy")
    for path in paths:
        test = np.load(path)
        score = str(round(euclid_score(train, test)))
        wrong_scores.append(score)

wrong_scores = np.array(wrong_scores, dtype=np.int64)
print(wrong_scores)
print(wrong_scores.mean())

[72 77 76 74 72]
74.2


# 4. growup

In [8]:
names = ['growup']

train = np.load("./video/vector_npy/vector_growup.npy")

wrong_scores = []
for name in names:
    paths = glob.glob(f"./직촬편집/{name}/*.npy")
    for path in paths:
        test = np.load(path)
        score = str(round(euclid_score(train, test)))
        wrong_scores.append(score)

wrong_scores = np.array(wrong_scores, dtype=np.int64)
print(wrong_scores)
print(wrong_scores.mean())

[64 69 70 65 63]
66.2


# 5. jungle_dance

In [9]:
names = ['jungle_dance']

train = np.load("./video/vector_npy/vector_jungle.npy")

wrong_scores = []
for name in names:
    paths = glob.glob(f"./직촬편집/{name}/*.npy")
    for path in paths:
        test = np.load(path)
        score = str(round(euclid_score(train, test)))
        wrong_scores.append(score)

wrong_scores = np.array(wrong_scores, dtype=np.int64)
print(wrong_scores)
print(wrong_scores.mean())

[80 82 77 72 73]
76.8


# 6. monster

In [10]:
names = ['monster']

train = np.load("./video/vector_npy/vector_monster.npy")

wrong_scores = []
for name in names:
    paths = glob.glob(f"./직촬편집/{name}/*.npy")
    for path in paths:
        test = np.load(path)
        score = str(round(euclid_score(train, test)))
        wrong_scores.append(score)

wrong_scores = np.array(wrong_scores, dtype=np.int64)
print(wrong_scores)
print(wrong_scores.mean())

[63 63 68 65 62]
64.2


# 7. octopus

In [11]:
names = ['octopus']

train = np.load("./video/vector_npy/vector_octopus.npy")

wrong_scores = []
for name in names:
    paths = glob.glob(f"./직촬편집/{name}/*.npy")
    for path in paths:
        test = np.load(path)
        score = str(round(euclid_score(train, test)))
        wrong_scores.append(score)

wrong_scores = np.array(wrong_scores, dtype=np.int64)
print(wrong_scores)
print(wrong_scores.mean())

[63 70 71 62 70]
67.2


# 8. pinkpong

In [12]:
names = ['pinkpong']

train = np.load("./video/vector_npy/vector_pinkpong.npy")

wrong_scores = []
for name in names:
    paths = glob.glob(f"./직촬편집/{name}/*.npy")
    for path in paths:
        test = np.load(path)
        score = str(round(euclid_score(train, test)))
        wrong_scores.append(score)

wrong_scores = np.array(wrong_scores, dtype=np.int64)
print(wrong_scores)
print(wrong_scores.mean())

[67 68 71 70 67]
68.6


# 9. poo

In [13]:
names = ['poo']

train = np.load("./video/vector_npy/vector_poo.npy")

wrong_scores = []
for name in names:
    paths = glob.glob(f"./직촬편집/{name}/*.npy")
    for path in paths:
        test = np.load(path)
        score = str(round(euclid_score(train, test)))
        wrong_scores.append(score)

wrong_scores = np.array(wrong_scores, dtype=np.int64)
print(wrong_scores)
print(wrong_scores.mean())

[76 78 79 75 76]
76.8


# 10. volcano

In [14]:
names = ['volcano']

train = np.load("./video/vector_npy/vector_volcano.npy")

wrong_scores = []
for name in names:
    paths = glob.glob(f"./직촬편집/{name}/*.npy")
    for path in paths:
        test = np.load(path)
        score = str(round(euclid_score(train, test)))
        wrong_scores.append(score)

wrong_scores = np.array(wrong_scores, dtype=np.int64)
print(wrong_scores)
print(wrong_scores.mean())

[63 70 68 65 69]
67.0
